version: "3.7"

services:

  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: python app.py

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: python-test
      APP_PORT: 4000
    
  server:
    image: getumbrel/community-app-store-hello-world:latest
    user: "1000:1000"
    init: true

